/**
 * Created by hazem on 17/01/2018.
 */
//login Actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
//Register Actions
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
//logout Actions
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
//FETCHING CONNECTED USER
export const CONNECTED_USER_REQUEST = 'CONNECTED_USER_REQUEST'
export const CONNECTED_USER_RECEIVE = 'CONNECTED_USER_RECEIVE'
export const NO_CONNECTED_USER = 'NO_CONNECTED_USER'
